include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    inference_failure_on_instance_creation: ignore
    use_setters_to_change_properties: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    constant_identifier_names: ignore
    strict_raw_type: ignore
