name: cart
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  get_storage: ^2.1.1
  json_annotation: ^4.8.1
  jwt_decoder: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0



flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env
