class EnLanguage {
  static Map<String, String> get language => {
        'home': 'Home',
        'welcome': 'Welcome, @name!',
        'welcome_description': 'Good to have you back!',
        'search': 'Search',
        'login': 'Log in',
        'logout': 'Log out',
        'user': 'User',
        'address': 'Address',
        'phone': 'Phone',
        'email': 'Email',
        'name': 'Name',
        'login_description': 'Please log in to continue',
        'username': 'Username',
        'password': 'Password',
        'error': 'Error',
        'error_description': 'An error has occurred, please try again',
        'error_login': 'Error logging in',
        'password_required': 'Password is required',
        'username_required': 'Username is required',
        'description': 'Description',
        'category': 'Category',
        'quantity': 'Quantity',
        'add_to_cart': 'Add to cart',
        'success': 'Success',
        'product_added_to_cart': 'Product added to cart',
        'failed_to_add_product_to_cart': 'Failed to add product to cart',
        'view_cart': 'View cart',
        'loading': 'Loading...',
        'failed_to_fetch_cart': 'Failed to fetch cart, please try again',
        'delete_from_cart': 'Delete from cart',
        'cart': 'Cart',
        'cart_empty': 'Your cart is empty',
        'cart_empty_description': 'Add products to the cart to continue',
        'cart_number': 'Cart #@number',
        'product_removed_from_cart': 'Product removed from cart',
        'failed_to_remove_product_from_cart':
            'Failed to remove product from cart',
      };
}
