class EsLanguage {
  static Map<String, String> get language => {
        'home': 'Inicio',
        'welcome': 'Bienvenido, @name!',
        'welcome_description': 'Que bueno tenerte de vuelta!',
        'search': 'Buscar',
        'login': 'Iniciar sesión',
        'logout': 'Cerrar sesión',
        'user': 'Usuario',
        'address': 'Dirección',
        'phone': 'Teléfono',
        'email': 'Correo electrónico',
        'name': 'Nombre',
        'login_description': 'Por favor, inicia sesión para continuar',
        'username': 'Nombre de usuario',
        'password': 'Contraseña',
        'error': 'Error',
        'error_description': 'Ha ocurrido un error, por favor intenta de nuevo',
        'error_login': 'Error al iniciar sesión',
        'password_required': 'La contraseña es requerida',
        'username_required': 'El nombre de usuario es requerido',
        'description': 'Descripción',
        'category': 'Categoría',
        'quantity': 'Cantidad',
        'add_to_cart': 'Agregar al carrito',
        'success': 'Éxito',
        'product_added_to_cart': 'Producto agregado al carrito',
        'failed_to_add_product_to_cart':
            'No se pudo agregar el producto al carrito',
        'view_cart': 'Ver carrito',
        'loading': 'Cargando...',
        'failed_to_fetch_cart':
            'No se pudo cargar el carrito, por favor intenta de nuevo',
        'delete_from_cart': 'Eliminar del carrito',
        'cart': 'Carrito',
        'cart_empty': 'Tu carrito está vacío',
        'cart_empty_description': 'Agrega productos al carrito para continuar',
        'cart_number': 'Carrito #@number',
        'product_removed_from_cart': 'Producto eliminado del carrito',
        'failed_to_remove_product_from_cart':
            'No se pudo eliminar el producto del carrito',
      };
}
